// PreToolUse hook generation for Claude Code in GraphWiki v2

import { writeFile, mkdir } from 'fs/promises';
import { join } from 'path';

/**
 * Generate PreToolUse hook for Claude Code
 *
 * This hook is invoked before each tool use by Claude Code.
 * It can inspect the tool call and modify behavior.
 */
export async function generatePreToolUseHook(
  outputPath: string,
  options: {
    enableGraphLookup?: boolean;
    enableTokenTracking?: boolean;
    enableContextEnrichment?: boolean;
  } = {}
): Promise<void> {
  const {
    enableGraphLookup = true,
    enableTokenTracking = true,
    enableContextEnrichment = true,
  } = options;

  const hook = generateHookContent(enableGraphLookup, enableTokenTracking, enableContextEnrichment);
  await mkdir(join(outputPath, '..'), { recursive: true });
  await writeFile(outputPath, hook, 'utf-8');
}

/**
 * Generate hook content
 */
function generateHookContent(
  enableGraphLookup: boolean,
  enableTokenTracking: boolean,
  enableContextEnrichment: boolean
): string {
  return `/**
 * GraphWiki PreToolUse Hook
 * Generated by GraphWiki v2
 *
 * This hook intercepts tool calls to provide:
 * - Graph-aware context lookup
 * - Token usage tracking
 * - Automatic context enrichment
 */

'use strict';

const GRAPHWIKI_STATE = {
  lastModified: null,
  tokenBudget: {
    max: 150000,
    used: 0,
    warningThreshold: 0.8
  }
};

/**
 * Main hook handler
 */
async function preToolUse({ tool, input, session }) {
  const toolName = tool.name;

  // Track token usage for LLM calls
  ${enableTokenTracking ? `
  if (isLlmTool(toolName)) {
    await trackTokenUsage(toolName, input);
  }
  ` : ''}

  // Enrich context with graph knowledge
  ${enableContextEnrichment ? `
  if (shouldEnrichContext(toolName)) {
    await enrichContext(input, session);
  }
  ` : ''}

  // Graph lookup for relevant tools
  ${enableGraphLookup ? `
  if (shouldLookupGraph(toolName)) {
    await graphLookup(toolName, input, session);
  }
  ` : ''}

  return { tool, input };
}

/**
 * Check if tool is an LLM call
 */
function isLlmTool(toolName) {
  return ['ask', 'complete', 'chat', 'anthropic', 'openai', 'google'].some(
    t => toolName.toLowerCase().includes(t)
  );
}

/**
 * Track token usage
 */
async function trackTokenUsage(toolName, input) {
  const estimate = estimateTokens(input);
  GRAPHWIKI_STATE.tokenBudget.used += estimate;

  if (GRAPHWIKI_STATE.tokenBudget.used > GRAPHWIKI_STATE.tokenBudget.max * GRAPHWIKI_STATE.tokenBudget.warningThreshold) {
    console.warn(\`[GraphWiki] Token budget warning: \${GRAPHWIKI_STATE.tokenBudget.used}/\${GRAPHWIKI_STATE.tokenBudget.max}\`);
  }
}

/**
 * Estimate tokens in input
 */
function estimateTokens(input) {
  if (typeof input === 'string') {
    return Math.ceil(input.length / 4);
  }
  if (typeof input === 'object') {
    return Math.ceil(JSON.stringify(input).length / 4);
  }
  return 0;
}

/**
 * Determine if context should be enriched
 */
function shouldEnrichContext(toolName) {
  const enrichmentTools = ['ask', 'read', 'search', 'grep', 'search'];
  return enrichmentTools.some(t => toolName.toLowerCase().includes(t));
}

/**
 * Enrich tool input with graph context
 */
async function enrichContext(input, session) {
  // Extract entities/terms from input
  const terms = extractTerms(input);

  if (terms.length > 0) {
    // Try to load relevant graph context
    const context = await loadGraphContext(terms);

    if (context && context.nodes.length > 0) {
      // Prepend context to input if significant
      const contextStr = formatContext(context);
      if (contextStr.length < 5000) {
        input.context = contextStr;
      }
    }
  }
}

/**
 * Extract search terms from input
 */
function extractTerms(input) {
  if (typeof input === 'string') {
    return input.split(/\\s+/).filter(t => t.length > 3);
  }
  if (typeof input === 'object') {
    return extractTerms(JSON.stringify(input));
  }
  return [];
}

/**
 * Load context from graph
 */
async function loadGraphContext(terms) {
  // This would connect to GraphWiki graph state
  // For now, return minimal structure
  return {
    nodes: [],
    edges: [],
    graphPath: '.graphwiki/graph.json'
  };
}

/**
 * Format context for tool input
 */
function formatContext(context) {
  if (context.nodes.length === 0) return '';
  return \`\\n\\n[GraphWiki Context]\\nRelated nodes: \${context.nodes.map(n => n.label).join(', ')}\\n\`;
}

/**
 * Determine if graph lookup should be performed
 */
function shouldLookupGraph(toolName) {
  const lookupTools = ['query', 'search', 'ask', 'read', 'grep'];
  return lookupTools.some(t => toolName.toLowerCase().includes(t));
}

/**
 * Perform graph lookup
 */
async function graphLookup(toolName, input, session) {
  // Look up relevant graph nodes for the tool context
  const query = extractQuery(input);
  if (query) {
    const nodes = await findRelevantNodes(query);
    if (nodes.length > 0) {
      session.set('graphwiki.nodes', nodes);
    }
  }
}

/**
 * Extract query from tool input
 */
function extractQuery(input) {
  if (typeof input === 'string') return input;
  if (typeof input === 'object') {
    return input.query || input.question || input.search || input.text || '';
  }
  return '';
}

/**
 * Find relevant nodes in graph
 */
async function findRelevantNodes(query) {
  // Simplified implementation
  // Real implementation would search the graph
  return [];
}

module.exports = { preToolUse };
`;
}

/**
 * Generate hook configuration for Claude Code
 */
export async function generateHookConfig(
  hooksDir: string,
  hookPath: string
): Promise<void> {
  await mkdir(hooksDir, { recursive: true });
  const config = {
    hooks: {
      'pre-tool-use': {
        path: hookPath,
        enabled: true,
      },
    },
  };
  await writeFile(
    join(hooksDir, 'graphwiki-hooks.json'),
    JSON.stringify(config, null, 2),
    'utf-8'
  );
}

/**
 * Install pre-tool-use hook
 */
export async function installPreToolUseHook(
  projectPath = process.cwd(),
  options = {}
): Promise<void> {
  const hooksDir = join(projectPath, '.claude', 'hooks');
  const hookPath = join(hooksDir, 'graphwiki-pre-tool-use.js');

  await generatePreToolUseHook(hookPath, options);
  await generateHookConfig(hooksDir, hookPath);

  console.log(`[GraphWiki] PreToolUse hook installed at: ${hookPath}`);
}
